language: node_js
node_js:
  - 7
sudo: false
before_script:
  - git config --global user.email "smuemd@gmail.com"
  - git config --global user.name "smuemd"
install:
  - npm install -g mocha
  - npm install
after_script:
  - npm run coveralls
